services:
  # Map tile server
  tileserver:
    image: maptiler/tileserver-gl:latest
    container_name: ${COMPOSE_PROJECT_NAME:-floodmap}-tileserver
    # No external port exposure in production
    volumes:
      - ${MAPS_HOST_PATH:-/mnt/backup/floodmap/data/maps}:/data:ro
      - ${MAPS_HOST_PATH:-/mnt/backup/floodmap/data/maps}/config.json:/config.json:ro
    environment:
      - TILESERVER_CONFIG=/config.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # FloodMap Web Application (serves website + API)
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-floodmap}-webapp
    ports:
      - "8000:8000"  # Always expose in production for reverse proxy
    volumes:
      # Mount elevation data to fixed container paths
      - ${ELEVATION_HOST_PATH:-/mnt/backup/floodmap/data/elevation/zst_compressed}:/app/data/elevation:ro
      # Mount precompressed elevation tiles  
      - ${PRECOMPRESSED_HOST_PATH:-/mnt/backup/floodmap/data/elevation/brotli_tiles}:/app/data/precompressed:ro
      # Mount maps data directory  
      - ${MAPS_HOST_PATH:-/mnt/backup/floodmap/data/maps}:/app/data/maps:ro
      # Mount cache directory
      - api-cache:/cache
    environment:
      # Core app config
      - WEBAPP_PORT=8000
      - TILESERVER_URL=http://tileserver:8080
      # All container paths are now fixed - no need for environment variables
      
      # Performance tuning (configurable)
      - ELEVATION_CACHE_SIZE=${ELEVATION_CACHE_SIZE:-100}
      - TILE_CACHE_SIZE=${TILE_CACHE_SIZE:-2000}
      
      # Environment and monitoring
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-}
      
      # System settings
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - tileserver
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Production security
    security_opt:
      - no-new-privileges:true
    # Resource limits (configurable)
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-20G}
          cpus: ${CPU_LIMIT:-2.0}

volumes:
  api-cache:
    driver: local

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME:-floodmap}-network