services:
  # Map tile server
  tileserver:
    image: maptiler/tileserver-gl:latest
    container_name: ${COMPOSE_PROJECT_NAME:-floodmap}-tileserver
    # No external port exposure in production
    volumes:
      - type: bind
        source: ${MAPS_HOST_PATH:-/mnt/backup/floodmap/data/maps}
        target: /data
        read_only: true
    environment:
      - TILESERVER_CONFIG=/data/config.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # FloodMap Web Application (serves website + API)
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-floodmap}-webapp
    ports:
      - "8000:8000"  # Always expose in production for reverse proxy
    volumes:
      # Mount elevation source data (raw SRTM files for runtime generation)
      - type: bind
        source: ${ELEVATION_SOURCE_PATH:-/mnt/backup/floodmap/data/elevation-source}
        target: /app/data/elevation-source
        read_only: true
      # Mount precompressed elevation tiles (Q10 optimized: 95% storage reduction)
      - type: bind
        source: ${ELEVATION_TILES_PATH:-/mnt/backup/floodmap/data/elevation-tiles}
        target: /app/data/elevation-tiles
        read_only: true
      # Mount base map data directory
      - type: bind
        source: ${BASE_MAPS_PATH:-/mnt/backup/floodmap/data/base-maps}
        target: /app/data/base-maps
        read_only: true
      # Mount cache directory
      - api-cache:/cache
    environment:
      # Core app config
      - WEBAPP_PORT=8000
      - TILESERVER_URL=http://tileserver:8080
      # All container paths are now fixed - no need for environment variables
      
      # Performance tuning (configurable)
      - ELEVATION_CACHE_SIZE=${ELEVATION_CACHE_SIZE:-100}
      - TILE_CACHE_SIZE=${TILE_CACHE_SIZE:-2000}
      
      # Environment and monitoring
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-}
      
      # System settings
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - tileserver
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Production security
    security_opt:
      - no-new-privileges:true
    # Resource limits (configurable)
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-20G}
          cpus: ${CPU_LIMIT:-2.0}

volumes:
  api-cache:
    driver: local

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME:-floodmap}-network
