services:
  # Map tile server
  tileserver:
    image: maptiler/tileserver-gl:latest
    container_name: ${COMPOSE_PROJECT_NAME:-floodmap}-tileserver
    volumes:
      - type: bind
        source: ${MAPS_HOST_PATH:-/mnt/backup/floodmap/data/maps}
        target: /data
        read_only: true
    environment:
      - TILESERVER_CONFIG=/data/config.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # FloodMap Web Application (serves website + API)
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-floodmap}-webapp
    # No external ports - reverse proxy handles external access
    expose:
      - "8000"
    volumes:
      # Mount elevation source data (raw SRTM files for runtime generation)
      - type: bind
        source: ${ELEVATION_SOURCE_PATH:-data/elevation-source}
        target: /app/data/elevation-source
        read_only: true
      # Mount precompressed elevation tiles (Q10 optimized)
      - type: bind
        source: ${ELEVATION_TILES_PATH:-data/elevation-tiles}
        target: /app/data/elevation-tiles
        read_only: true
      # Mount base map data directory
      - type: bind
        source: ${BASE_MAPS_PATH:-data/base-maps}
        target: /app/data/base-maps
        read_only: true
      # Mount cache directory
      - api-cache:/cache
    environment:
      # Core app config
      - WEBAPP_PORT=8000
      - TILESERVER_URL=http://tileserver:8080
      # All container paths are now fixed - no need for environment variables
      
      # Performance tuning (configurable)
      - ELEVATION_CACHE_SIZE=${ELEVATION_CACHE_SIZE:-100}
      - TILE_CACHE_SIZE=${TILE_CACHE_SIZE:-2000}
      
      # Environment and monitoring
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-}
      
      # System settings
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - tileserver
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 300s  # 5 minutes to allow for elevation data copy
    # Production security (only when ENVIRONMENT=production)
    security_opt:
      - no-new-privileges:true
    # Resource limits (configurable)
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-20G}
          cpus: ${CPU_LIMIT:-2.0}

volumes:
  api-cache:
    driver: local

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME:-floodmap}-network
