services:
  # Map tile server
  tileserver:
    image: maptiler/tileserver-gl:latest
    container_name: ${COMPOSE_PROJECT_NAME:-floodmap}-tileserver
    volumes:
      - /mnt/backup/floodmap:/data:ro
      - /mnt/backup/floodmap/config.json:/config.json:ro
    environment:
      - TILESERVER_CONFIG=/config.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # FloodMap Web Application (serves website + API)
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-floodmap}-webapp
    # No external ports - reverse proxy handles external access
    expose:
      - "8000"
    volumes:
      # Mount elevation data (no longer copied at build time)
      - /mnt/backup/floodmap/elevation:/app/output/elevation:ro
      # Mount MBTiles file (too large for build-time copy)
      - /mnt/backup/floodmap/usa-complete.mbtiles:/app/output/usa-complete.mbtiles:ro
      # Mount cache directory
      - api-cache:/cache
    environment:
      # Core app config
      - WEBAPP_PORT=8000
      - TILESERVER_URL=http://tileserver:8080
      - PROJECT_ROOT=/app
      - ELEVATION_DATA_DIR=output/elevation
      
      # Performance tuning (configurable)
      - ELEVATION_CACHE_SIZE=${ELEVATION_CACHE_SIZE:-100}
      - TILE_CACHE_SIZE=${TILE_CACHE_SIZE:-2000}
      
      # Environment and monitoring
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-}
      
      # System settings
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - tileserver
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 300s  # 5 minutes to allow for elevation data copy
    # Production security (only when ENVIRONMENT=production)
    security_opt:
      - no-new-privileges:true
    # Resource limits (configurable)
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-20G}
          cpus: ${CPU_LIMIT:-2.0}

volumes:
  api-cache:
    driver: local

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME:-floodmap}-network