[project]
name = "floodmap"
version = "0.1.0"
description = "floodmap based on your location"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geopy>=2.4.1",
    "python-fasthtml>=0.6.9",
]
